#!/usr/bin/env python3
"""Bundles the web app into a single self-contained HTML file.

The result runs straight from the file system in Chrome: the ES modules are
concatenated into one classic script, the stylesheet is inlined and the sensor
firmware is embedded, so the page never needs `fetch()` or a web server.
"""

import base64
import re
import shutil
import webbrowser
from pathlib import Path
import time

WEBAPP = Path(__file__).resolve().parent
REPO = WEBAPP.parents[2]
FIRMWARE = WEBAPP / "hex" / "tmf8829_application.hex"
OUTPUT = REPO / "html" / "tmf8829" / "tmf8829_web_gui.html"
MEDIAPIPE_SOURCE = WEBAPP / "mediapipe"
MEDIAPIPE_OUTPUT = OUTPUT.parent / "mediapipe"
HAND_ASSETS_DEV_URL = "'../../../html/tmf8829/mediapipe/tmf8829_hand_assets.js'"
HAND_ASSETS_URL = "'mediapipe/tmf8829_hand_assets.js'"

# Dependency order: a module must come after everything it imports.
MODULES = [
    "crc16.js",
    "registers.js",
    "intelhex.js",
    "frames.js",
    "corefw.js",
    "h5.js",
    "render.js",
    "hand.js",
    "logging.js",
    "tmf8829.js",
    "webusb.js",
    "app.js",
]

IMPORT_START = re.compile(r"^\s*import\b")
IMPORT_END = re.compile(r"from\s+'[^']*';\s*$")
EXPORT_PREFIX = re.compile(r"^export\s+")


def strip_module_syntax(source: str, name: str) -> str:
    """Removes import statements and the `export` keyword from a module."""
    lines = []
    in_import = False
    for line in source.splitlines():
        if in_import:
            in_import = not IMPORT_END.search(line)
            continue
        if IMPORT_START.match(line):
            in_import = not IMPORT_END.search(line)
            continue
        lines.append(EXPORT_PREFIX.sub("", line))
    return f"// ---- {name} " + "-" * max(0, 68 - len(name)) + "\n" + "\n".join(lines)


def build_hand_assets() -> None:
    """Packs MediaPipe (library, WASM, hand model) into one classic script that also loads from file://."""
    loader = (MEDIAPIPE_SOURCE / "vision_wasm_internal.js").read_text(encoding="utf-8")
    vision = (MEDIAPIPE_SOURCE / "vision_bundle.cjs").read_text(encoding="utf-8")
    wasm = base64.b64encode((MEDIAPIPE_SOURCE / "vision_wasm_internal.wasm").read_bytes()).decode("ascii")
    model = base64.b64encode((MEDIAPIPE_SOURCE / "hand_landmarker.task").read_bytes()).decode("ascii")

    script = (
        "// Generated by build_and_run.py - do not edit.\n"
        "// MediaPipe tasks-vision 0.10.14 and hand_landmarker float16/1, Copyright Google LLC,\n"
        "// Apache License 2.0, see LICENSE in this folder.\n"
        f"{loader}\n"
        "window.TMF8829_HAND_ASSETS = {\n"
        "vision: function () {\nvar module = { exports: {} };\nvar exports = module.exports;\n"
        f"{vision}\n"
        "return module.exports;\n},\n"
        f'wasm: "{wasm}",\n'
        f'model: "{model}",\n'
        "};\n"
    )
    MEDIAPIPE_OUTPUT.mkdir(parents=True, exist_ok=True)
    output = MEDIAPIPE_OUTPUT / "tmf8829_hand_assets.js"
    output.write_text(script, encoding="utf-8")
    shutil.copyfile(MEDIAPIPE_SOURCE / "LICENSE", MEDIAPIPE_OUTPUT / "LICENSE")
    print(f"wrote {output.relative_to(REPO)} ({output.stat().st_size / 1024 / 1024:.1f} MB)")


def main() -> None:
    html = (WEBAPP / "index.html").read_text(encoding="utf-8")
    css = (WEBAPP / "css" / "style.css").read_text(encoding="utf-8")
    firmware = FIRMWARE.read_text(encoding="utf-8").strip()

    bundle = "\n\n".join(
        strip_module_syntax((WEBAPP / "js" / name).read_text(encoding="utf-8"), name)
        for name in MODULES
    )
    if "</script" in bundle or "</script" in firmware:
        raise SystemExit("source contains a literal </script and would break the bundle")
    if HAND_ASSETS_DEV_URL not in bundle:
        raise SystemExit("hand.js changed: the bundler could not rewrite the hand assets path")
    bundle = bundle.replace(HAND_ASSETS_DEV_URL, HAND_ASSETS_URL)
    build_hand_assets()

    html = html.replace(
        '<link rel="stylesheet" href="css/style.css">',
        f"<style>\n{css}\n</style>",
    )
    html = html.replace(
        "By default <code>tmf8829/hex/tmf8829_application.hex</code> is fetched from the server.",
        "<code>tmf8829_application.hex</code> is embedded in this page; select a file only to override it.",
    )
    html = html.replace(
        '<script type="module" src="js/app.js"></script>',
        '<script type="text/plain" id="embeddedFirmware">\n'
        f"{firmware}\n"
        "</script>\n"
        f"<script>\n(function () {{\n'use strict';\n{bundle}\n}})();\n</script>",
    )
    if "js/app.js" in html or "css/style.css" in html:
        raise SystemExit("index.html changed: the bundler could not inline all assets")

    OUTPUT.write_text(html, encoding="utf-8")
    print(f"wrote {OUTPUT.relative_to(REPO)} ({OUTPUT.stat().st_size / 1024:.0f} kB)")
    print("Opening web browser with created file...")
    webbrowser.open(OUTPUT.as_uri())


if __name__ == "__main__":
    main()
    time.sleep(3)  # to see output file location
