/*****************************************************************************
 * Hand landmark and pinch detection on the TMF8829 signal image (MediaPipe).
 * Port of https://github.com/ams-OSRAM/tmf8829_app_hand_pinch_detection/blob/main/tmf8829_hand_detection.py
 *
 * MediaPipe Hand Landmarker model and library: Copyright Google LLC,
 * Apache License 2.0 (https://www.apache.org/licenses/LICENSE-2.0).
 *****************************************************************************/

import { getPixelXYZ, getPixelXYZExact } from './render.js';

// Classic script generated by build_and_run.py; a classic <script> also loads from file:// pages.
// build_and_run.py rewrites this path to 'mediapipe/tmf8829_hand_assets.js' for the bundled page.
const HAND_ASSETS_URL = '../../../html/tmf8829/mediapipe/tmf8829_hand_assets.js';

const IMAGE_WIDTH = 800;
const IMAGE_HEIGHT = 600;
const PINCH_LINE_PX = 100;
const PINCH_DETECT_PX = 50;
const FINGERTIPS = { 4: 'Thumb', 8: 'Index', 12: 'Middle', 16: 'Ring', 20: 'Pinky' };
// PINCH_COLOR is the page accent (--accent in style.css).
const PINCH_COLOR = '#fd5000';
const INFO_COLOR = '#4fc3f7';

/** Same as cv2.bilateralFilter(src, d=5, sigmaColor=100, sigmaSpace=15) with replicated borders. */
function bilateralFilter(src, rows, cols, radius = 2, sigmaColor = 100, sigmaSpace = 15) {
  const out = new Float32Array(src.length);
  const colorCoeff = -0.5 / (sigmaColor * sigmaColor);
  const spaceCoeff = -0.5 / (sigmaSpace * sigmaSpace);
  for (let y = 0; y < rows; y++) {
    for (let x = 0; x < cols; x++) {
      const center = src[y * cols + x];
      let sum = 0;
      let weightSum = 0;
      for (let dy = -radius; dy <= radius; dy++) {
        const yy = Math.min(rows - 1, Math.max(0, y + dy));
        for (let dx = -radius; dx <= radius; dx++) {
          const r2 = dx * dx + dy * dy;
          if (r2 > radius * radius) continue;
          const xx = Math.min(cols - 1, Math.max(0, x + dx));
          const value = src[yy * cols + xx];
          const diff = value - center;
          const weight = Math.exp(r2 * spaceCoeff + diff * diff * colorCoeff);
          sum += value * weight;
          weightSum += weight;
        }
      }
      out[y * cols + x] = sum / weightSum;
    }
  }
  return out;
}

/** Bicubic tap indices and weights matching OpenCV INTER_CUBIC (a = -0.75). */
function cubicTaps(srcSize, dstSize) {
  const a = -0.75;
  const index = new Int32Array(dstSize * 4);
  const weight = new Float32Array(dstSize * 4);
  const scale = srcSize / dstSize;
  for (let d = 0; d < dstSize; d++) {
    const s = (d + 0.5) * scale - 0.5;
    const base = Math.floor(s);
    const t = s - base;
    const w0 = ((a * (t + 1) - 5 * a) * (t + 1) + 8 * a) * (t + 1) - 4 * a;
    const w1 = ((a + 2) * t - (a + 3)) * t * t + 1;
    const w2 = ((a + 2) * (1 - t) - (a + 3)) * (1 - t) * (1 - t) + 1;
    const weights = [w0, w1, w2, 1 - w0 - w1 - w2];
    for (let k = 0; k < 4; k++) {
      index[d * 4 + k] = Math.min(srcSize - 1, Math.max(0, base - 1 + k));
      weight[d * 4 + k] = weights[k];
    }
  }
  return { index, weight };
}

function resizeCubic(src, srcW, srcH, dstW, dstH) {
  const tx = cubicTaps(srcW, dstW);
  const ty = cubicTaps(srcH, dstH);
  const tmp = new Float32Array(srcH * dstW);
  for (let y = 0; y < srcH; y++) {
    for (let x = 0; x < dstW; x++) {
      let sum = 0;
      for (let k = 0; k < 4; k++) sum += src[y * srcW + tx.index[x * 4 + k]] * tx.weight[x * 4 + k];
      tmp[y * dstW + x] = sum;
    }
  }
  const dst = new Float32Array(dstW * dstH);
  for (let y = 0; y < dstH; y++) {
    for (let k = 0; k < 4; k++) {
      const row = ty.index[y * 4 + k] * dstW;
      const w = ty.weight[y * 4 + k];
      for (let x = 0; x < dstW; x++) dst[y * dstW + x] += tmp[row + x] * w;
    }
  }
  return dst;
}

function loadClassicScript(url) {
  return new Promise((resolve, reject) => {
    const script = document.createElement('script');
    script.src = url;
    script.onload = () => resolve();
    script.onerror = () => reject(new Error(`Could not load ${url}`));
    document.head.appendChild(script);
  });
}

function base64ToBytes(text) {
  const binary = atob(text);
  const bytes = new Uint8Array(binary.length);
  for (let i = 0; i < binary.length; i++) bytes[i] = binary.charCodeAt(i);
  return bytes;
}

/** Returns the xyz (mm) of the in-range sensor pixel nearest to a normalized landmark, or null. */
function landmarkXYZ(pixels, landmark, zMin, zMax) {
  const rows = pixels.length;
  const cols = pixels[0].length;
  const col0 = Math.min(cols - 1, Math.max(0, Math.trunc(landmark.x * cols)));
  const row0 = Math.min(rows - 1, Math.max(0, Math.trunc(landmark.y * rows)));
  let best = null;
  let bestDistance = Infinity;
  // The landmark may sit on an edge pixel without a valid return, so also check the neighbours.
  for (let dy = -1; dy <= 1; dy++) {
    for (let dx = -1; dx <= 1; dx++) {
      const row = row0 + dy;
      const col = col0 + dx;
      if (row < 0 || row >= rows || col < 0 || col >= cols) continue;
      const pixel = pixels[row][col];
      const distance = pixel.peaks[0]?.distance;
      if (!distance) continue;
      const xyz = getPixelXYZ(row, col, distance, cols, rows, pixel.fovCorrection ?? null);
      if (xyz.z < zMin || xyz.z > zMax) continue;
      const offset = dx * dx + dy * dy;
      if (offset < bestDistance) {
        best = xyz;
        bestDistance = offset;
      }
    }
  }
  return best;
}

function drawText(context, text, x, y, color, size) {
  context.font = `bold ${size}px system-ui, sans-serif`;
  context.fillStyle = color;
  context.textBaseline = 'alphabetic';
  context.textAlign = 'left';
  context.fillText(text, x, y);
}

/** MediaPipe feeds images through WebGL even on the CPU delegate, so a WebGL-capable canvas is required. */
function createWebGLCanvas() {
  const candidates = [];
  if (typeof OffscreenCanvas !== 'undefined') candidates.push(() => new OffscreenCanvas(1, 1));
  candidates.push(() => document.createElement('canvas'));
  for (const create of candidates) {
    try {
      const probe = create();
      const gl = probe.getContext('webgl2') || probe.getContext('webgl');
      if (gl) {
        gl.getExtension('WEBGL_lose_context')?.loseContext();
        return create();
      }
    } catch {
      // Try the next canvas type.
    }
  }
  throw new Error(
    'WebGL is not available in this browser. Enable hardware acceleration ' +
      '(chrome://settings/system) and check chrome://gpu for WebGL status.',
  );
}

export class HandDetector {
  constructor({ onLog = () => {} } = {}) {
    this.onLog = onLog;
    this.landmarker = null;
    this.loading = null;
    this.error = null;
    this.lastTimestamp = 0;
  }

  /** Loads MediaPipe, its WASM runtime and the hand model from the embedded asset script on first use. */
  load() {
    if (!this.loading) {
      this.onLog('Loading MediaPipe hand landmarker...');
      this.loading = (async () => {
        const glCanvas = createWebGLCanvas();
        await loadClassicScript(HAND_ASSETS_URL);
        const assets = window.TMF8829_HAND_ASSETS;
        delete window.TMF8829_HAND_ASSETS;
        const vision = assets.vision();
        // The asset script already defined self.ModuleFactory; a preset Module.wasmBinary avoids any fetch.
        self.Module = { wasmBinary: base64ToBytes(assets.wasm) };
        this.landmarker = await vision.HandLandmarker.createFromOptions(
          { wasmLoaderPath: '', wasmBinaryPath: 'vision_wasm_internal.wasm' },
          {
            baseOptions: { modelAssetBuffer: base64ToBytes(assets.model) },
            numHands: 2,
            runningMode: 'VIDEO',
            canvas: glCanvas,
          },
        );
        this.onLog('Hand landmarker ready');
      })().catch((error) => {
        this.error = error;
        this.onLog(`Could not load hand landmarker: ${error.message}`);
      });
    }
    return this.loading;
  }

  /**
   * Renders the signal image of `pixels` into `canvas` and, when `detect` is
   * set, overlays hand landmarks and pinch state.
   */
  render(canvas, pixels, { zMin, zMax, detect }) {
    const rows = pixels.length;
    const cols = rows ? pixels[0].length : 0;
    const result = { hands: 0, pinch: false, averageDistance: null, usesSignal: true, fingertips: [] };
    if (!rows || !cols) return result;

    const signal = new Float32Array(rows * cols);
    let zSum = 0;
    let zCount = 0;
    for (let row = 0; row < rows; row++) {
      for (let col = 0; col < cols; col++) {
        const pixel = pixels[row][col];
        const peak = pixel.peaks[0];
        if (!peak || !peak.distance) continue;
        const { z } = getPixelXYZExact(row, col, peak.distance, cols, rows, pixel.fovCorrection ?? null);
        if (z < zMin || z > zMax) continue;
        if (peak.signal === null) result.usesSignal = false;
        signal[row * cols + col] = peak.signal ?? peak.snr;
        zSum += z;
        zCount++;
      }
    }

    const filtered = bilateralFilter(signal, rows, cols);
    let min = Infinity;
    let max = -Infinity;
    for (const value of filtered) {
      if (value < min) min = value;
      if (value > max) max = value;
    }
    const span = max > min ? 255 / (max - min) : 0;
    for (let i = 0; i < filtered.length; i++) filtered[i] = (filtered[i] - min) * span;

    const large = resizeCubic(filtered, cols, rows, IMAGE_WIDTH, IMAGE_HEIGHT);
    canvas.width = IMAGE_WIDTH;
    canvas.height = IMAGE_HEIGHT;
    const context = canvas.getContext('2d');
    const image = context.createImageData(IMAGE_WIDTH, IMAGE_HEIGHT);
    for (let i = 0; i < large.length; i++) {
      const gray = Math.min(255, Math.max(0, Math.round(large[i])));
      image.data[i * 4] = gray;
      image.data[i * 4 + 1] = gray;
      image.data[i * 4 + 2] = gray;
      image.data[i * 4 + 3] = 255;
    }
    context.putImageData(image, 0, 0);

    if (!detect) {
      drawText(context, 'Hand detection disabled', 50, 100, INFO_COLOR, 28);
    } else if (this.error) {
      drawText(context, 'Hand model unavailable', 50, 100, '#ff0000', 28);
    } else if (!this.landmarker) {
      drawText(context, 'Loading hand model...', 50, 100, INFO_COLOR, 28);
    } else {
      this.lastTimestamp = Math.max(performance.now(), this.lastTimestamp + 1);
      let detection;
      try {
        detection = this.landmarker.detectForVideo(canvas, this.lastTimestamp);
      } catch (error) {
        this.error = error;
        this.onLog(`Hand detection failed: ${error.message}`);
        detection = {};
      }
      result.hands = detection.landmarks?.length ?? 0;
      for (const landmarks of detection.landmarks ?? []) {
        if (this.drawHand(context, landmarks)) result.pinch = true;
        result.fingertips.push({
          thumb: landmarkXYZ(pixels, landmarks[4], zMin, zMax),
          index: landmarkXYZ(pixels, landmarks[8], zMin, zMax),
        });
      }
    }

    if (zCount) {
      result.averageDistance = Math.trunc(zSum / zCount);
      drawText(context, `Average distance ${result.averageDistance} mm`, 50, 50, INFO_COLOR, 28);
    } else {
      drawText(context, `No object from ${zMin} mm to ${zMax} mm`, 50, 50, INFO_COLOR, 28);
    }
    return result;
  }

  /** Draws one hand and returns true if thumb and index tip form a pinch. */
  drawHand(context, landmarks) {
    landmarks.forEach((landmark, index) => {
      const cx = Math.trunc(landmark.x * IMAGE_WIDTH);
      const cy = Math.trunc(landmark.y * IMAGE_HEIGHT);
      context.fillStyle = '#00ff00';
      context.beginPath();
      context.arc(cx, cy, 5, 0, 2 * Math.PI);
      context.fill();
      if (FINGERTIPS[index]) drawText(context, FINGERTIPS[index], cx + 10, cy - 10, '#ffff00', 18);
    });

    const x1 = Math.trunc(landmarks[4].x * IMAGE_WIDTH);
    const y1 = Math.trunc(landmarks[4].y * IMAGE_HEIGHT);
    const x2 = Math.trunc(landmarks[8].x * IMAGE_WIDTH);
    const y2 = Math.trunc(landmarks[8].y * IMAGE_HEIGHT);
    const distance = Math.hypot(x2 - x1, y2 - y1);

    if (distance < PINCH_LINE_PX) {
      context.strokeStyle = '#0000ff';
      context.lineWidth = 3;
      context.beginPath();
      context.moveTo(x1, y1);
      context.lineTo(x2, y2);
      context.stroke();
    }
    if (distance < PINCH_DETECT_PX) {
      drawText(context, 'PINCH DETECTED', 50, 100, PINCH_COLOR, 28);
      return true;
    }
    return false;
  }
}
