name: Deploy HTML to GitHub Pages

on:
  push:
    branches:
      - main  # Trigger the action when you push to the main branch
  workflow_dispatch: # <--- Adds the manual run button

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Point this to your specific "html" directory
          path: './html'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
